/**
 * @file test_add_sub.cpp
 * @brief Unit tests for ADD, ADC, SUB and SBC CPU instructions.
 *
 * @license GPLv3 (see LICENSE file)
 */

#include <gtest/gtest.h>

#include "boyboy/cpu/opcodes.h"
#include "boyboy/cpu/registers.h"

// Helpers
#include "helpers/cpu_fixtures.h"
#include "helpers/cpu_params.h"

using boyboy::cpu::Opcode;
using boyboy::cpu::Reg8Name;

using boyboy::test::cpu::ALUOperandType;
using boyboy::test::cpu::R8ALUParam;
using boyboy::test::cpu::R8Test;

// -----------------------------
// Test types
// -----------------------------
using AddR8Test  = R8Test<R8ALUParam>;
using AddHLTest  = R8Test<R8ALUParam>;
using AddImmTest = R8Test<R8ALUParam>;
using AdcR8Test  = R8Test<R8ALUParam>;
using AdcHLTest  = R8Test<R8ALUParam>;
using AdcImmTest = R8Test<R8ALUParam>;
using SubR8Test  = R8Test<R8ALUParam>;
using SubHLTest  = R8Test<R8ALUParam>;
using SubImmTest = R8Test<R8ALUParam>;
using SbcR8Test  = R8Test<R8ALUParam>;
using SbcHLTest  = R8Test<R8ALUParam>;
using SbcImmTest = R8Test<R8ALUParam>;

// -----------------------------
// Test definitions
// -----------------------------
TEST_P(AddR8Test, Works) { run_test(); }
TEST_P(AddHLTest, Works) { run_test(); }
TEST_P(AddImmTest, Works) { run_test(); }
TEST_P(AdcR8Test, Works) { run_test(); }
TEST_P(AdcHLTest, Works) { run_test(); }
TEST_P(AdcImmTest, Works) { run_test(); }
TEST_P(SubR8Test, Works) { run_test(); }
TEST_P(SubHLTest, Works) { run_test(); }
TEST_P(SubImmTest, Works) { run_test(); }
TEST_P(SbcR8Test, Works) { run_test(); }
TEST_P(SbcHLTest, Works) { run_test(); }
TEST_P(SbcImmTest, Works) { run_test(); }

// -----------------------------
// Parameter instantiations
// -----------------------------

// ADD A, r8
INSTANTIATE_TEST_SUITE_P(AddInstructions,
                         AddR8Test,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_B,
                                 .src            = Reg8Name::B,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0xFE,
                                 .expected_value = 0x0F,
                                 .expect_c       = true,
                                 .name           = "B_CarryOverflow",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_C,
                                 .src            = Reg8Name::C,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0xEF,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "C_ZeroFlagSet",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_D,
                                 .src            = Reg8Name::D,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x0F,
                                 .expected_value = 0x20,
                                 .expect_h       = true,
                                 .name           = "D_HalfCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0x11,
                                 .expected_value = 0x22,
                                 .name           = "A_Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0x0F,
                                 .expected_value = 0x1E,
                                 .expect_h       = true,
                                 .name           = "A_HalfCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0xFF,
                                 .expected_value = 0xFE,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_Overflow",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_E,
                                 .src            = Reg8Name::E,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x01,
                                 .src_value      = 0xFF,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "E_OverflowZero",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_H,
                                 .src            = Reg8Name::H,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x01,
                                 .expected_value = 0x12,
                                 .name           = "H_Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_L,
                                 .src            = Reg8Name::L,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x0A,
                                 .expected_value = 0x1B,
                                 .name           = "L_Normal",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// ADD A, [HL]
INSTANTIATE_TEST_SUITE_P(AddInstructions,
                         AddHLTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0000,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .expected_value = 0x01,
                                 .name           = "Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0123,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .expected_value = 0x10,
                                 .expect_h       = true,
                                 .name           = "HalfCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x4567,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .name           = "Zero",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x89AB,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x10,
                                 .expected_value = 0x0F,
                                 .expect_c       = true,
                                 .name           = "OverflowCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0xCDEF,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x01,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "OverflowHalfCarryZero",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// ADD A, n8
INSTANTIATE_TEST_SUITE_P(AddInstructions,
                         AddImmTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .expected_value = 0x01,
                                 .name           = "Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .expected_value = 0x10,
                                 .expect_h       = true,
                                 .name           = "HalfCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .name           = "Zero",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x10,
                                 .expected_value = 0x0F,
                                 .expect_c       = true,
                                 .name           = "OverflowCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADD_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x01,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "OverflowHalfCarryZero",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// ADC A, r8
INSTANTIATE_TEST_SUITE_P(AdcInstructions,
                         AdcR8Test,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0x55,
                                 .carry_in       = false,
                                 .expected_value = 0xAA,
                                 .name           = "A_A_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0x55,
                                 .carry_in       = true,
                                 .expected_value = 0xAB,
                                 .name           = "A_A_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_B,
                                 .src            = Reg8Name::B,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x10,
                                 .expect_h       = true,
                                 .name           = "A_B_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_B,
                                 .src            = Reg8Name::B,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x11,
                                 .expect_h       = true,
                                 .name           = "A_B_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_C,
                                 .src            = Reg8Name::C,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x7F,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x80,
                                 .expect_h       = true,
                                 .name           = "A_C_OverflowBit7_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_C,
                                 .src            = Reg8Name::C,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x7F,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x81,
                                 .expect_h       = true,
                                 .name           = "A_C_OverflowBit7_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_D,
                                 .src            = Reg8Name::D,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .name           = "A_D_Zero_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_D,
                                 .src            = Reg8Name::D,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .carry_in       = true,
                                 .expected_value = 0x01,
                                 .name           = "A_D_Zero_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_E,
                                 .src            = Reg8Name::E,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_E_CarryOut_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_E,
                                 .src            = Reg8Name::E,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x01,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_E_CarryOut_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_H,
                                 .src            = Reg8Name::H,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x10,
                                 .expect_h       = true,
                                 .name           = "A_H_HalfCarry_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_H,
                                 .src            = Reg8Name::H,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x11,
                                 .expect_h       = true,
                                 .name           = "A_H_HalfCarry_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_L,
                                 .src            = Reg8Name::L,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x12,
                                 .src_value      = 0x34,
                                 .carry_in       = false,
                                 .expected_value = 0x46,
                                 .name           = "A_L_Normal_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_L,
                                 .src            = Reg8Name::L,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x12,
                                 .src_value      = 0x34,
                                 .carry_in       = true,
                                 .expected_value = 0x47,
                                 .name           = "A_L_Normal_WithCarry",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// ADC A, [HL]
INSTANTIATE_TEST_SUITE_P(AddInstructions,
                         AdcHLTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0000,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x01,
                                 .name           = "NormalNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0000,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x02,
                                 .name           = "NormalCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0123,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x10,
                                 .expect_h       = true,
                                 .name           = "HalfCarryNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0123,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x11,
                                 .expect_h       = true,
                                 .name           = "HalfCarryCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x4567,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .name           = "ZeroNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x4567,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .carry_in       = true,
                                 .expected_value = 0x01,
                                 .expect_z       = false,
                                 .name           = "NoZeroCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x89AB,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x10,
                                 .carry_in       = false,
                                 .expected_value = 0x0F,
                                 .expect_c       = true,
                                 .name           = "OverflowNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x89AB,
                                 .initial_a      = 0xFE,
                                 .src_value      = 0x10,
                                 .carry_in       = true,
                                 .expected_value = 0x0F,
                                 .expect_c       = true,
                                 .name           = "OverflowCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0xCDEF,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "OverflowZeroNoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0xCDEF,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x00,
                                 .carry_in       = true,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "OverflowZeroCarryIn",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// ADC A, n8
INSTANTIATE_TEST_SUITE_P(AddInstructions,
                         AdcImmTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x01,
                                 .name           = "NormalNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x02,
                                 .name           = "NormalCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x10,
                                 .expect_h       = true,
                                 .name           = "HalfCarryNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x11,
                                 .expect_h       = true,
                                 .name           = "HalfCarryCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .name           = "ZeroNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x00,
                                 .carry_in       = true,
                                 .expected_value = 0x01,
                                 .expect_z       = false,
                                 .name           = "NoZeroCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x10,
                                 .carry_in       = false,
                                 .expected_value = 0x0F,
                                 .expect_c       = true,
                                 .name           = "OverflowNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFE,
                                 .src_value      = 0x10,
                                 .carry_in       = true,
                                 .expected_value = 0x0F,
                                 .expect_c       = true,
                                 .name           = "OverflowCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "OverflowZeroNoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::ADC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0x00,
                                 .carry_in       = true,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "OverflowZeroCarryIn",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// SUB A, r8
INSTANTIATE_TEST_SUITE_P(SubInstructions,
                         SubR8Test,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_B,
                                 .src            = Reg8Name::B,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x12,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "B_Underflow",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_C,
                                 .src            = Reg8Name::C,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x02,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "C_HalfCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_D,
                                 .src            = Reg8Name::D,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x11,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "D_Zero",
                             },

                             // Normal tests
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0xFF,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "A_Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_E,
                                 .src            = Reg8Name::E,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x01,
                                 .expected_value = 0x10,
                                 .expect_n       = true,
                                 .name           = "E_Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_H,
                                 .src            = Reg8Name::H,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x0A,
                                 .expected_value = 0x07,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "H_Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_L,
                                 .src            = Reg8Name::L,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x11,
                                 .src_value      = 0x0F,
                                 .expected_value = 0x02,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "L_Normal",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// SUB A, [HL]
INSTANTIATE_TEST_SUITE_P(SubInstructions,
                         SubHLTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0000,
                                 .initial_a      = 0x02,
                                 .src_value      = 0x01,
                                 .expected_value = 0x01,
                                 .expect_n       = true,
                                 .name           = "Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0123,
                                 .initial_a      = 0x01,
                                 .src_value      = 0x01,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "Zero",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x4567,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "HalfCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x89AB,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x10,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0xCDEF,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x11,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowCarryHalfCarry",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// SUB A, n8
INSTANTIATE_TEST_SUITE_P(SubInstructions,
                         SubImmTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x02,
                                 .src_value      = 0x01,
                                 .expected_value = 0x01,
                                 .expect_n       = true,
                                 .name           = "Normal",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x01,
                                 .src_value      = 0x01,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "Zero",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "HalfCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x10,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SUB_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x11,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowCarryHalfCarry",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// SBC A, r8
INSTANTIATE_TEST_SUITE_P(SbcInstructions,
                         SbcR8Test,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0x55,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "A_A_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_A,
                                 .src            = Reg8Name::A,
                                 .src_value      = 0x55,
                                 .carry_in       = true,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_A_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_B,
                                 .src            = Reg8Name::B,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "A_B_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_B,
                                 .src            = Reg8Name::B,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x0E,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "A_B_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_C,
                                 .src            = Reg8Name::C,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_C_Underflow_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_C,
                                 .src            = Reg8Name::C,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x00,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0xFE,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_C_Underflow_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_D,
                                 .src            = Reg8Name::D,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x01,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "A_D_Zero_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_D,
                                 .src            = Reg8Name::D,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x01,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_D_Zero_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_E,
                                 .src            = Reg8Name::E,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0xFF,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "A_E_Zero_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_E,
                                 .src            = Reg8Name::E,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0xFF,
                                 .src_value      = 0xFF,
                                 .carry_in       = true,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "A_E_Zero_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_H,
                                 .src            = Reg8Name::H,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "A_H_HalfBorrow_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_H,
                                 .src            = Reg8Name::H,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x0E,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "A_H_HalfBorrow_WithCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_L,
                                 .src            = Reg8Name::L,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x20,
                                 .src_value      = 0x10,
                                 .carry_in       = false,
                                 .expected_value = 0x10,
                                 .expect_n       = true,
                                 .name           = "A_L_Normal_NoCarry",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_L,
                                 .src            = Reg8Name::L,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x20,
                                 .src_value      = 0x10,
                                 .carry_in       = true,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "A_L_Normal_WithCarry",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// SBC A, [HL]
INSTANTIATE_TEST_SUITE_P(SubInstructions,
                         SbcHLTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0000,
                                 .initial_a      = 0x02,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x01,
                                 .expect_n       = true,
                                 .name           = "NormalNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0000,
                                 .initial_a      = 0x03,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x01,
                                 .expect_n       = true,
                                 .name           = "NormalCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0123,
                                 .initial_a      = 0x01,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "ZeroNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x0123,
                                 .initial_a      = 0x02,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "ZeroCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x4567,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "HalfCarryNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x4567,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x0E,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "HalfCarryCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x89AB,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x10,
                                 .carry_in       = false,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0x89AB,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x0F,
                                 .carry_in       = true,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0xCDEF,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x11,
                                 .carry_in       = false,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "HalfCarryUnderflowNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_AT_HL,
                                 .operand_type   = ALUOperandType::IndirectHL,
                                 .dst            = Reg8Name::A,
                                 .src_addr       = 0xCDEF,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x10,
                                 .carry_in       = true,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "HalfCarryUnderflowCarryIn",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);

// SBC A, n8
INSTANTIATE_TEST_SUITE_P(SubInstructions,
                         SbcImmTest,
                         ::testing::Values(
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x02,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x01,
                                 .expect_n       = true,
                                 .name           = "NormalNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x03,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x01,
                                 .expect_n       = true,
                                 .name           = "NormalCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x01,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "ZeroNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x02,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x00,
                                 .expect_z       = true,
                                 .expect_n       = true,
                                 .name           = "ZeroCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = false,
                                 .expected_value = 0x0F,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "HalfCarryNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x01,
                                 .carry_in       = true,
                                 .expected_value = 0x0E,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .name           = "HalfCarryCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x10,
                                 .carry_in       = false,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x0F,
                                 .src_value      = 0x0F,
                                 .carry_in       = true,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "UnderflowCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x11,
                                 .carry_in       = false,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "HalfCarryUnderflowNoCarryIn",
                             },
                             R8ALUParam{
                                 .opcode         = Opcode::SBC_A_N8,
                                 .operand_type   = ALUOperandType::Immediate,
                                 .dst            = Reg8Name::A,
                                 .initial_a      = 0x10,
                                 .src_value      = 0x10,
                                 .carry_in       = true,
                                 .expected_value = 0xFF,
                                 .expect_n       = true,
                                 .expect_h       = true,
                                 .expect_c       = true,
                                 .name           = "HalfCarryUnderflowCarryIn",
                             }),
                         boyboy::test::cpu::param_name<R8ALUParam>);