/**
 * @file instructions.cpp
 * @brief CPU instructions tables for the BoyBoy emulator.
 *
 * @license GPLv3 (see LICENSE file)
 */

#include "boyboy/core/cpu/instructions_table.h"

namespace boyboy::core::cpu {

const std::array<Instruction, 256> InstructionTable::Opcodes = []() {
    std::array<Instruction, 256> table{};

    // Autogenerated unprefixed opcodes table from Opcodes.json
#include "generated/opcodes.inc"

    return table;
}();
static_assert(InstructionTable::Opcodes.size() == 256, "Opcodes table must have 256 entries");

const std::array<Instruction, 256> InstructionTable::CBOpcodes = []() {
    std::array<Instruction, 256> table{};

    // Autogenerated CB-prefixed opcodes table from Opcodes.json
#include "generated/cbopcodes.inc"

    return table;
}();
static_assert(InstructionTable::CBOpcodes.size() == 256, "CB Opcodes table must have 256 entries");

} // namespace boyboy::core::cpu