name: Tests

on: 
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    name: Build & Test (${{ matrix.preset }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        preset: [release]

    steps:
      - name: Workflow info
        run: |
          echo "Triggered by branch: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Actor: $GITHUB_ACTOR"
          echo "Event name: $GITHUB_EVENT_NAME"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake libsdl2-dev libopengl-dev

      - name: Cache CMake
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/CMake
            build/
          key: ${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('CMakeLists.txt', 'CMakePresets.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.preset }}-

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build project
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Run tests
        run: ctest --preset ${{ matrix.preset }}
